src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'messages')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $sender = null;

    #[ORM\ManyToOne(inversedBy: 'messageur')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $receiver = null;

    #[ORM\Column]
    private ?bool $isRead = false;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getSender(): ?User
    {
        return $this->sender;
    }

    public function setSender(?User $sender): static
    {
        $this->sender = $sender;

        return $this;
    }

    public function getReceiver(): ?User
    {
        return $this->receiver;
    }

    public function setReceiver(?User $receiver): static
    {
        $this->receiver = $receiver;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->isRead;
    }

    public function setIsRead(bool $isRead): self
    {
        $this->isRead = $isRead;

        return $this;
    }

}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
#[ApiResource]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Events $Event = null;

    #[ORM\Column(length: 255)]
    private ?string $FirstName = null;

    #[ORM\Column(length: 255)]
    private ?string $LastName = null;


    #[ORM\Column(length: 255)]
    private ?string $reservationNumber = null;

    #[ORM\Column]
    private ?int $numberOfpeople = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEvent(): ?Events
    {
        return $this->Event;
    }
   
    public function __toString(): string
    {
        return $this->Event ? $this->Event->__toString() : 'No Event';
    }

    public function setEvent(?Events $Event): static
    {
        $this->Event = $Event;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): static
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): static
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getReservationNumber(): ?string
    {
        return $this->reservationNumber;
    }

    public function setReservationNumber(string $reservationNumber): static
    {
        $this->reservationNumber = $reservationNumber;

        return $this;
    }

    public function getNumberOfpeople(): ?int
    {
        return $this->numberOfpeople;
    }

    public function setNumberOfpeople(int $numberOfpeople): static
    {
        $this->numberOfpeople = $numberOfpeople;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }
    
}

src/Form/MessageType.php
<?php 

// src/Form/MessageType.php

namespace App\Form;

use App\Entity\Message;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('content', TextareaType::class, [
                'attr' => ['rows' => 5], // Adjust as needed for the display
            ])
            ->add('receiver', null, [
                'label' => 'Destinataire',
                'choice_label' => 'email', // Adjust based on how you want to display the receiver
            ]);
            // ->add('created_at', DateTimeType::class, [
            //     'data' => new \DateTime('now', new \DateTimeZone('Europe/Paris')), // Set the default value to the current datetime in your time zone

            //     'widget' => 'single_text',
            //     'attr' => ['class' => 'js-datetimepicker'], // Optional: you can add a CSS class for a datetime picker
                
            // ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
        ]);
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use Exception;
use DateTimeZone;
use App\Entity\User;
use DateTimeImmutable;
use App\Entity\Message;
use App\Form\MessageType;
use Psr\Log\LoggerInterface;
use App\Repository\UserRepository;
use App\Repository\MessageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MessageController extends AbstractController
{
    #[Route('/message', name: 'app_message')]
    public function index(): Response
    {
        return $this->render('message/index.html.twig', [
            'controller_name' => 'MessageController',
        ]);
    }

    
    // Crée un nouveau message.
#[Route('/message/new', name: 'message_new')]
public function newMessage(Request $request, EntityManagerInterface $entityManager, UserRepository $userRepository): Response
{
    $message = new Message();
    $message->setIsRead(false); // Initialise le message comme non lu
    // Récupère tous les utilisateurs pour peupler le menu déroulant des destinataires
    $users = $userRepository->findAll();

    $form = $this->createForm(MessageType::class, $message);

    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        // Obtient l'utilisateur actuellement connecté comme expéditeur
        $sender = $this->getUser();

        // Définit l'expéditeur et la date et heure actuelles
        $message->setSender($sender);
        $createdAt = new DateTimeImmutable('now', new DateTimeZone('Europe/Paris'));
        $message->setCreatedAt($createdAt);
        // Renseigne les autres champs (par exemple, contenu, destinataire) selon vos besoins

        // Gère l'enregistrement du message
        $entityManager->persist($message);
        $entityManager->flush();

        $this->addFlash('success', 'Message envoyé avec succès!');
        return $this->redirectToRoute('member_area');
    }

    return $this->render('message/new.html.twig', [
        'form' => $form->createView(),
    ]);
}

// Répond à un message existant.
#[Route('/message/reply/{message}', name: 'message_reply')]
public function reply(Message $message, Request $request, EntityManagerInterface $entityManager, LoggerInterface $logger): Response
{
    // Récupère l'utilisateur destinataire en fonction du message
    $receiver = $message->getReceiver();

    $replyMessage = new Message();
    $replyMessage->setReceiver($receiver);

    $form = $this->createForm(MessageType::class, $replyMessage);

    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $sender = $this->getUser();
        $createdAt = new DateTimeImmutable('now', new DateTimeZone('Europe/Paris'));

        $replyMessage
            ->setSender($sender)
            ->setCreatedAt($createdAt)
            ->setContent($form['content']->getData());

        try {
            $entityManager->persist($replyMessage);
            $entityManager->flush();

            $this->addFlash('success', 'Réponse envoyée avec succès!');
            return $this->redirectToRoute('message_show_conversation', ['id' => $receiver->getId()]);
        } catch (Exception $e) {
            $this->addFlash('error', "Une erreur s'est produite lors de l'enregistrement du message : " . $e->getMessage());
            $logger->error("Erreur lors de l'enregistrement du message : " . $e->getMessage());
        }
    }

    return $this->render('message/reply.html.twig', [
        'form' => $form->createView(),
        'message' => $message,
    ]);
}

// Affiche les conversations de l'utilisateur.
#[Route('message/conversations', name: 'message_conversations')]
public function showConversations(MessageRepository $messageRepository): Response
{
    // Obtient l'utilisateur actuellement connecté
    $user = $this->getUser();

    // Si l'utilisateur n'est pas connecté ou introuvable, lance une exception appropriée ou gère le cas
    if (!$user) {
        throw $this->createNotFoundException('Utilisateur non trouvé');
    }

    // Récupère les conversations pour l'utilisateur actuel
    $conversations = $messageRepository->findConversationsForUser($user);

    // Extrait les utilisateurs des conversations et obtient le nombre de messages non lus
    $usersWithConversations = [];
    foreach ($conversations as $conversation) {
        $currentUser = $conversation['user'];
        $unreadCount = $messageRepository->getUnreadCountForUserInConversation($user, $currentUser);
        $usersWithConversations[] = [
            'user' => $currentUser,
            'unreadCount' => $unreadCount
        ];
    }

    return $this->render('message/conversations_list.html.twig', [
        'usersWithConversations' => $usersWithConversations,
    ]);
}
// Affiche une conversation spécifique avec un utilisateur donné.
#[Route('/conversation/{id}', name: 'message_show_conversation', requirements: ['id' => '\d+'])]
public function showConversation(int $id, MessageRepository $messageRepository, EntityManagerInterface $entityManager): Response
{
    // Récupère l'utilisateur actuellement connecté
    $user = $this->getUser();

    // Recherche l'utilisateur avec lequel la conversation doit être affichée
    $conversationUser = $entityManager->getRepository(User::class)->find($id);

    // Récupère les messages pour la conversation donnée
    $messages = $messageRepository->findMessagesForConversation($user, $conversationUser);

    // Marque les messages comme lus
    foreach ($messages as $message) {
        if (!$message->getIsRead() && $message->getReceiver() === $user) {
            $message->setIsRead(true);
            $entityManager->persist($message);
        }
    }
    $entityManager->flush();

    return $this->render('message/conversation.html.twig', [
        'messages' => $messages,
        'conversationUser' => $conversationUser,
    ]);
}

}

templates/message/conversation.html.twig
{% extends 'base.html.twig' %}
{% block javascripts %}
    <script>
        {{ parent() }}
    </script>
{% endblock %}
{% block title %}
    Conversation avec 
    {% if conversationUser.firstName and conversationUser.lastName %}
        {{ conversationUser.firstName }} {{ conversationUser.lastName }}
    {% else %}
        {{ conversationUser.email }}
    {% endif %}
{% endblock %}
{% block body %}
	<div class="breadcrumb">
    <a href="{{path('member_area')}}" class="area-back">Espace membre ></a>
    <a href="{{path('message_conversations')}}"class="area-back">Listes des conversations</a>
</div>
       <h2 class="actus-title activite">Conversation avec 
        {% if conversationUser.firstName and conversationUser.lastName %}
            {{ conversationUser.firstName }} {{ conversationUser.lastName }}
        {% else %}
            {{ conversationUser.email }}
        {% endif %}
    </h2>
    <div class="conversation-container">
        {% for message in messages|reverse %}
            <div class="message {% if message.sender == app.user %}sent{% else %}received{% endif %}">
                <span class="message-sender">
                    {% if message.sender.avatar %}
                    <img src="/{{message.sender.getAvatar}}" class="avatar rounded-circle mr-3" alt="">
                    {% else %}
                        <img src="/images/avatar.png" class="avatar " alt="Default Avatar">
                    {% endif %}
                    {% if message.sender == app.user %}
                        Vous 
                    {% else %}
                    {% if message.sender.firstName and message.sender.lastName %}
                        {{ message.sender.firstName }} {{ message.sender.lastName }} 
                    {% else %}
                        {{ message.sender.email }}
                    {% endif %}
                    {% endif %}
                </span>
                <span class="message-date"> {{ message.createdAt|date('Y-m-d H:i') }}</span>
                <div class="message-content">{{ message.content }}</div>
            </div>
        {% endfor %}
    </div>
    {{ render(controller('App\\Controller\\MessageController::reply', { 'receiver': conversationUser })) }}

{% endblock %}

templates/message/conversations.html.twig
{% extends 'base.html.twig' %}
{% block javascripts %}
<script>
    {{ parent() }}
</script>
 
{% endblock %}
{% block body %}
	<div class="breadcrumb">
    <a href="{{path('member_area')}}" class="area-back">Espace membre ></a>
</div>
    <h2 class="actus-title activite">Vos conversations</h2>
    <ul>
        {% for conversation in conversations %}
            <li>
                <strong>Conversation avec {{ conversation.user.firstName }} {{ conversation.user.lastName }}</strong>
                <ul>
                    {% for message in conversation.messages %}
                        <li>
                            {{ message.content }} - {{ message.created_at|date('Y-m-d H:i:s') }}
                        </li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/message/conversations_list.html.twig
{% extends 'base.html.twig' %}
{% block javascripts %}
<script>
    {{ parent() }}
</script>
{% endblock %}
 {% block title %}
   Conversations
{% endblock %}
{% block body %}
	<div class="breadcrumb">
    <a href="{{path('member_area')}}" class="area-back">Espace membre ></a>
</div>
    <div class="container">
        <h2 class="actus-title activite">Conversations</h2>
        {% if usersWithConversations|length > 0 %}
            <ul class="conversations list-group">
                {% for conversation in usersWithConversations %}
                    <li class="list-group-item d-flex align-items-center">
                        {% if conversation.user.avatar %}
                            <img src="/{{conversation.user.getAvatar}}" class="avatar rounded-circle mr-3" alt="{{ conversation.user.firstName }} {{ conversation.user.lastName }}">
                        {% else %}
                            <img src="/images/avatar.png" class="avatar rounded-circle mr-3" alt="Default Avatar">
                        {% endif %}
                        <div>
                            <a class="text-dark" href="{{ path('message_show_conversation', {'id': conversation.user.id}) }}">
                                {% if conversation.user.firstName and conversation.user.lastName %}
                                    {{ conversation.user.firstName }} {{ conversation.user.lastName }}
                                {% else %}
                                    {{ conversation.user.email }}
                                {% endif %}
                            </a>
                            {% if conversation.unreadCount > 0 %}
                                <span class="badge badge-primary ml-2">{{ conversation.unreadCount }} messages non lu </span>
                            {% endif %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="text-muted">No conversations found.</p>
        {% endif %}
    </div>
{% endblock %}

templates/message/new.html.twig
{# templates/message/new.html.twig #}

{% extends 'base.html.twig' %}
{% block javascripts %}
<script>
    {{ parent() }}
</script>
 
{% endblock %}
{% block title %}Envoyer un message{% endblock %}

{% block body %}
	<div class="breadcrumb">
    <a href="{{path('member_area')}}" class="area-back">Espace membre ></a>
</div>
<div class="forms-container">
  <h1 class="actus-title activite">Envoyer un message</h1>

  {{ form_start(form) }}
  {{ form_label(form.content,'Message :') }}
  {{ form_widget(form.content) }}
  <button type="submit" class="button">Envoyer</button>
  {{ form_end(form) }}
</div>
{% endblock %}

templates/message/reply.html.twig
{% for message in app.flashes('error') %}
    <div class="alert alert-danger">
        {{ message }}
    </div>
{% endfor %}
<div class="forms-container">

  {{ form_start(form, {'action': path('message_reply', {'message': message.id})}) }}
    
  {{ form_label(form.content,'Message:') }}
  {{ form_widget(form.content) }}
   <div style="display: none;">
    {{ form_label(form.receiver) }}
    {{ form_widget(form.receiver) }}
  </div>
  <button type="submit" class="button-2 reply">Envoyer</button>
  {{ form_end(form) }}
  </form>
</div>